export const events = {
    status: 200,
    data: [
        {
            date: new Date("Wed, 27 July 2016 13:30:00"),
            name: "Default Name",
            location: "UW CSE2 271",
            sponsor: null,
            attendees: 100,
            description: "text text and a lot more text. Actually this might be too much random text. Imma go now. Ha im back. Imma go for real now. Got you again rofl. Ok im bored now, signing off. ** Mic drop ** ^-^",
            image: "https://picsum.photos/200/300",
        },
        {
            date: new Date("Wed, 27 July 2019 13:30:00"),
            name: "Better Name",
            location: "UW CSE2 271",
            sponsor: "DubHacks",
            attendees: 100,
            description: "This event is MEMBERS ONLY. Actually though, should we add another column in the table for these types of events? But here is much more text than last time and should overflow some stuff! text text and a lot more text. Actually this might be too much random text. Imma go now. Ha im back. Imma go for real now. Got you again rofl. Ok im bored now, signing off. ** Mic drop ** ^-^",
            image: "Image",
        },
        {
            date: new Date("Wed, 27 July 2019 13:30:00"),
            name: "Workshop",
            location: "UW Hub Building Room 12345",
            sponsor: null,
            attendees: 1000,
            description: "text text and a lot more text. A",
            image: "https://picsum.photos/200/300",
        },
        {
            date: new Date("Wed, 27 July 2016 13:30:00"),
            name: "Default Name1",
            location: "UW CSE2 271",
            sponsor: null,
            attendees: 100,
            description: "text text and a lot more text. Actually this might be too much random text. Imma go now. Ha im back. Imma go for real now. Got you again rofl. Ok im bored now, signing off. ** Mic drop ** ^-^",
            image: "https://picsum.photos/200/300",
        },
        {
            date: new Date("Wed, 27 July 2019 13:30:00"),
            name: "Better Name1",
            location: "UW CSE2 271",
            sponsor: "DubHacks",
            attendees: 100,
            description: "This event is MEMBERS ONLY. Actually though, should we add another column in the table for these types of events? But here is much more text than last time and should overflow some stuff! text text and a lot more text. Actually this might be too much random text. Imma go now. Ha im back. Imma go for real now. Got you again rofl. Ok im bored now, signing off. ** Mic drop ** ^-^",
            image: null,
        },
        {
            date: new Date("Wed, 27 July 2019 13:30:00"),
            name: "Workshop1",
            location: "UW Hub Building Room 12345",
            sponsor: null,
            attendees: 1000,
            description: "text text and a lot more text. A",
            image: "https://picsum.photos/200/300",
        },
    ],
};

export const people = {
    status: 200,
    data: [
        {
            name: "Default Name",
            id: 0,
            joinDate: new Date("Wed, 27 July 2019 13:30:00"),
            active: true,
            year: "Freshman",
            role: "Club Lead",
            email: "hcpuw@uw.edu",
            team: "Default Team",
            leftDate: new Date("Wed, 27 July 2019 13:30:00"),
            image: "https://picsum.photos/200/300",
        },
        {
            name: "Better Name",
            id: 1,
            joinDate: new Date("Wed, 27 July 2019 13:30:00"),
            active: false,
            year: "Sophomore",
            role: "Co-Chair",
            email: "hcpuw@uw.edu",
            team: "Default Team",
            leftDate: new Date("Wed, 27 July 2019 13:30:00"),
            image: "https://picsum.photos/200/300",
        },
        {
            name: "Default Name",
            id: 2,
            joinDate: new Date("Wed, 27 July 2019 13:30:00"),
            active: true,
            year: "Senior",
            role: "Club Lead",
            email: "hcpuw@uw.edu",
            team: "Default Team",
            leftDate: new Date("Wed, 27 July 2019 13:30:00"),
            image: "https://picsum.photos/200/300",
        },
        {
            name: "2nd Better Name",
            id: 3,
            joinDate: new Date("Wed, 27 July 2019 13:30:00"),
            active: true,
            year: "Senior",
            role: "Co-Chair",
            email: "hcpuw@uw.edu",
            team: "Default Team",
            leftDate: new Date("Wed, 27 July 2019 13:30:00"),
            image: "https://picsum.photos/200/300",
        },
        {
            name: "5th Default Name",
            id: 4,
            joinDate: new Date("Wed, 27 July 2019 13:30:00"),
            active: true,
            year: "Junior",
            role: "Education Lead",
            email: "hcpuw@uw.edu",
            team: "Default Team",
            leftDate: new Date("Wed, 27 July 2019 13:30:00"),
            image: "https://picsum.photos/200/300",
        },
        {
            name: "Default Name",
            id: 5,
            joinDate: new Date("Wed, 27 July 2019 13:30:00"),
            active: true,
            year: "Junior",
            role: "Club Lead",
            email: "hcpuw@uw.edu",
            team: "Default Team",
            leftDate: new Date("Wed, 27 July 2019 13:30:00"),
            image: "https://picsum.photos/200/300",
        },
        {
            name: "Default Name",
            id: 6,
            joinDate: new Date("Wed, 27 July 2019 13:30:00"),
            active: true,
            year: "Junior",
            role: "Club Lead",
            email: "hcpuw@uw.edu",
            team: "Default Team",
            leftDate: new Date("Wed, 27 July 2019 13:30:00"),
            image: "https://picsum.photos/200/300",
        },
        {
            name: "Default Name",
            id: 7,
            joinDate: new Date("Wed, 27 July 2019 13:30:00"),
            active: true,
            year: "Junior",
            role: "Club Lead",
            email: "hcpuw@uw.edu",
            team: "Default Team",
            leftDate: new Date("Wed, 27 July 2019 13:30:00"),
            image: "https://picsum.photos/200/300",
        },
        {
            name: "Default Name",
            id: 8,
            joinDate: new Date("Wed, 27 July 2019 13:30:00"),
            active: true,
            year: "Junior",
            role: "Club Lead",
            email: "hcpuw@uw.edu",
            team: "Default Team",
            leftDate: new Date("Wed, 27 July 2019 13:30:00"),
            image: "https://picsum.photos/200/300",
        },
        {
            name: "Default Name",
            id: 9,
            joinDate: new Date("Wed, 27 July 2019 13:30:00"),
            active: true,
            year: "Junior",
            role: "Club Lead",
            email: "hcpuw@uw.edu",
            team: "Default Team",
            leftDate: new Date("Wed, 27 July 2019 13:30:00"),
            image: "https://picsum.photos/200/300",
        },
        {
            name: "Default Name",
            id: 10,
            joinDate: new Date("Wed, 27 July 2019 13:30:00"),
            active: true,
            year: "Junior",
            role: "Club Lead",
            email: "hcpuw@uw.edu",
            team: "Default Team",
            leftDate: new Date("Wed, 27 July 2019 13:30:00"),
            image: "https://picsum.photos/200/300",
        },
        {
            name: "Default Name",
            id: 11,
            joinDate: new Date("Wed, 27 July 2019 13:30:00"),
            active: true,
            year: "Junior",
            role: "Club Lead",
            email: "hcpuw@uw.edu",
            team: "Default Team",
            leftDate: new Date("Wed, 27 July 2019 13:30:00"),
            image: "https://picsum.photos/200/300",
        },
    ],
};
 
export const projects = {
    status: 200,
    data: [
        {
            name: "Project Name",
            startDate: new Date("Wed, 27 July 2019 13:30:00"),
            endDate: new Date("Wed, 27 July 2019 13:30:00"),
            completed: false,
            category: "Website",
            pm: "student",
            gitLink: "github.com",
            description: "a new project that we started a while back ago. The goal of this project is to make a new sample of. We hope to gain stronger skills in frontend through increased web development skills.",
            members: "person 1, person 2",
            image: "https://picsum.photos/200/300",
        },
        {
            name: "Project Name",
            startDate: new Date("Wed, 27 July 2019 13:30:00"),
            endDate: new Date("Wed, 27 July 2019 13:30:00"),
            completed: false,
            category: "Website",
            pm: "student",
            gitLink: "github.com",
            description: "a new project that we started a while back ago. The goal of this project is to make a new sample of. We hope to gain stronger skills in frontend through increased web development skills.",
            members: "person 1, person 2",
            image: "https://picsum.photos/200/300",
        },
        {
            name: "Project Name",
            startDate: new Date("Wed, 27 July 2019 13:30:00"),
            endDate: new Date("Wed, 27 July 2019 13:30:00"),
            completed: false,
            category: "Website",
            pm: "student",
            gitLink: "github.com",
            description: "a new project that we started a while back ago. The goal of this project is to make a new sample of. We hope to gain stronger skills in frontend through increased web development skills.",
            members: "person 1, person 2",
            image: "https://picsum.photos/200/300",
        },
        {
            name: "Project Name",
            startDate: new Date("Wed, 27 July 2019 13:30:00"),
            endDate: new Date("Wed, 27 July 2019 13:30:00"),
            completed: false,
            category: "Website",
            pm: "student",
            gitLink: "github.com",
            description: "a new project that we started a while back ago. The goal of this project is to make a new sample of. We hope to gain stronger skills in frontend through increased web development skills.",
            members: "person 1, person 2",
            image: "https://picsum.photos/200/300",
        },
        {
            name: "Project Name",
            startDate: new Date("Wed, 27 July 2019 13:30:00"),
            endDate: new Date("Wed, 27 July 2019 13:30:00"),
            completed: false,
            category: "Website",
            pm: "student",
            gitLink: "github.com",
            description: "a new project that we started a while back ago. The goal of this project is to make a new sample of. We hope to gain stronger skills in frontend through increased web development skills.",
            members: "person 1, person 2",
            image: "https://picsum.photos/200/300",
        },
        {
            name: "Project Name",
            startDate: new Date("Wed, 27 July 2019 13:30:00"),
            endDate: new Date("Wed, 27 July 2019 13:30:00"),
            completed: false,
            category: "Website",
            pm: "student",
            gitLink: "github.com",
            description: "a new project that we started a while back ago. The goal of this project is to make a new sample of. We hope to gain stronger skills in frontend through increased web development skills.",
            members: "person 1, person 2",
            image: "https://picsum.photos/200/300",
        },
    ],
};
