import Head from "next/head";
import { Box, Flex} from "@chakra-ui/react";
import type { ReactElement } from "react";

import Header from "../components/Header";
import Footer from "../components/Footer";

export default function Layout({ children }: { children: ReactElement }) {
    return (
        <>
            <Head>
                <title>Husky Coding Project</title>
                <meta
                    name="Husky Coding Project Club Website"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Flex flexDirection='column' minH='100vh' bgGradient='linear(to-b, brand.blue, brand.dark_blue)'>
                <Box position='fixed' width='100vw' backdropFilter='blur(10px)' backdropBlur='10px' zIndex='100'>
                    <Header />
                </Box>
                <Box marginTop='150px' width='100vw'>
                    {children}
                </Box>
                <Footer />
            </Flex>
        </>
    );
}
